# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scoreLVM <- function(data, p, scoreFun, mu, dmu, S, dS, indexCoef, indexEndo, indexIntercept, indexLP, indexManifest, indiv) {
    .Call(lavaReduce_scoreLVM, data, p, scoreFun, mu, dmu, S, dS, indexCoef, indexEndo, indexIntercept, indexLP, indexManifest, indiv)
}

